POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "testuser@example.com",
    "password": "Password123!",
    "phone": "1234567890",
    "role": "admin"
} 

### Login Request
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "Password123!"
}
###
POST http://localhost:5000/api/v1/societies
Content-Type: application/json

{
  "name": "Green Valley",
  "address": "Indore",
  "city": "Indore",
  "state": "MP",
  "pincode": "452001"
}
### Add Society with Authorization
POST http://localhost:5000/api/v1/societies
Content-Type: application/json
Authorization: Bearer YOUR_COPIED_TOKEN_HERE

{
  "name": "Green Valley",
  "address": "Indore",
  "city": "Indore",
  "state": "MP",
  "pincode": "452001"
}